name: 🚀 Deploy Meltview to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 167.88.36.53 >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: ssh root@167.88.36.53 "/root/deploy.sh"
